steps:
    - name: 'ghcr.io/depot/cli:latest'
      args:
          - build
          - '--project'
          - $_DEPOT_PROJECT_ID
          - '--build-platform'
          - linux/amd64
          - '--tag'
          - '$_IMAGE'
          - '--load'
          - .
      id: Build image
      secretEnv:
          - DEPOT_TOKEN
    - name: 'massfice/bun-vue-trpc-dev-utils:2.1.0-amd64'
      args:
          - '-c'
          - 'deploy name=$_DEPLOY_NAME owner=$_DEPLOY_INFRA_REPO_OWNER repo=$_DEPLOY_INFRA_REPO token=$$GITHUB_TOKEN image=$_IMAGE path=$_DEPLOY_PATH template=$_DEPLOY_TEMPLATE'
      id: Deploy
      entrypoint: bash
      secretEnv:
          - GITHUB_TOKEN

images:
    - '$_IMAGE'

substitutions:
    _IMAGE: 'gcr.io/$PROJECT_ID/your-image-name:$COMMIT_SHA'
    _DEPOT_PROJECT_ID: projectId
    _DEPLOY_NAME: name
    _DEPLOY_INFRA_REPO_OWNER: owner
    _DEPLOY_INFRA_REPO: infra
    _DEPLOY_PATH: path
    _DEPLOY_TEMPLATE: dGVtcGxhdGU=
    _GITHUB_TOKEN_VERSION: projects/$PROJECT_ID/secrets/github_secret/versions/1
    _DEPOT_TOKEN_VERSION: projects/$PROJECT_ID/secrets/depot_token/versions/1

availableSecrets:
    secretManager:
        - versionName: $_DEPOT_TOKEN_VERSION
          env: DEPOT_TOKEN
        - versionName: $_GITHUB_TOKEN_VERSION
          env: GITHUB_TOKEN
